name: medico_ai
description: "Offline Medical Chatbot"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.7
  provider: ^6.1.5
  path_provider: ^2.1.2
  sqflite: ^2.3.2
  flutter_markdown: ^0.6.20
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  process_run: ^0.14.1
  http: ^1.2.0 # for downloading model files
  file_picker: ^10.2.0
  path: ^1.8.3
  ffi: 2.1.4
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.5.0
  web: ^1.1.0
  js_interop: ^0.1.0-beta

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - models/
    - mediapipe/
    - mediapipe/wasm/
    # Evaluation datasets
    - evaluation/dataset/questions.csv
  uses-material-design: true
